version: '3'
services:
  pytouchwithcuda:
    build: .
    container_name: pytouchwithcuda
    command: bash -c "nvidia-smi && tail -f /dev/null"
    runtime: nvidia
    tty: true
    volumes:
      - .:/src
    shm_size: '8gb'